{{- if .Values.rbac.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "arbeitsinspektor.fullname" . }}
  labels:
    {{- include "arbeitsinspektor.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - "events.k8s.io"
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - "arbeitsinspektor.ghcr.io"
  resources:
    - businesshours
  verbs:
    - list
    - get
- apiGroups:
    - "apps"
  resources:
    - deployments
  verbs:
    - list
    - get
- apiGroups:
    - "apps"
  resources:
    - "deployments/scale"
  verbs:
    - patch
{{- end -}}
