apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "arbeitsinspektor.fullname" . }}
  labels:
    {{- include "arbeitsinspektor.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          serviceAccountName: {{ include "arbeitsinspektor.serviceAccountName" . }}
          restartPolicy: "Never"
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
      backoffLimit: 0
