name: Erlang

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:25-slim
    steps:
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install make
      - uses: actions/checkout@v3
      - name: Build and Test
        run: make build
